spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2s

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [requestId=%X{requestId}] - %msg%n"
  level:
    root: INFO
    br.com.gabrieloliveira: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: WARN